workspace:
    base: /data/service
    path: .

pipeline:
    test:
        image: golang:1.13.6
        commands:
            - pwd
            - go env
            - go version
            - go test -v
    build:
        image: golang:1.13.6
        environment:
            - GO111MODULE=on
            - GOPROXY=https://goproxy.cn,direct
        commands:
            - CGO_ENABLED=0 go build -o api
            - ls -l
    docker:
        image: golang:1.13.6
        commands:
            - docker build -t api:v1 .
            - docker images
    run:
        image: golang:1.13.6
        commands:
            - docker ps
            - docker stop go-api
            - docker ps
            - docker run -d --rm --name go-api -p 8001:8001 api:v1
