---
kind: pipeline
name: drone

workspace:
    base: /data/service
    path: .

steps:
    - name: test
        image: golang:1.13.6
        commands:
            - pwd
            - go version
            - go test -v

# name: go-api
# workspace:
#     base: /data/service
#     path: .
# pipeline:
#     test:
#         image: golang:1.13.6
#         commands:
#             - pwd
#             - go version
#             - go test -v
#     build:
#         image: golang:1.13.6
#         environment:
#             - GO111MODULE=on
#             - GOPROXY=https://goproxy.cn,direct
#         commands:
#             - go env
#             - CGO_ENABLED=0 go build -o api
#             - ls -l
#     run:
#         image: appleboy/drone-ssh
#         settings:
#             host: host
#             port: 22
#             user: ssh_name
#             key: ssh_key
#         script:
#             - cd /home/songwenwen/www/api && git pull origin master
#             - pwd && ls -l
#             - CGO_ENABLED=0 go build -o api
#             - docker build -t api:v1 .
#             - docker rm -f go-api || true
#             - docker run -d --rm --name go-api -p 8001:8001 api:v1
