workspace:
  base: /home/songwenwen/www/api
  path: .

pipeline:
  build:
    image: golang: 1.13
    # # pull: true
    # environment:
    #   - KEY=VALUE
    # secrets: [key1, key2]
    commands:
      - pwd
      - go env
      - go version
      - go build
