pipeline:
    test:
        image: golang:1.13.6
        commands:
            - echo $HOST
            - echo $USERNAME
            - echo $PASSWORD
            - pwd
            - go version
            - go test -v
        environment:
            - HOST:
                from_secret: host
            - USERNAME:
                from_secret: ssh_name
            - PASSWORD:
                from_secret: ssh_key
    build:
        image: golang:1.13.6
        environment:
            - GO111MODULE=on
            - GOPROXY=https://goproxy.cn,direct
        commands:
            - go env
            - CGO_ENABLED=0 go build -o api
            - ls -l
    run:
        image: appleboy/drone-ssh
        settings:
            host:
                from_secret: host
            port: 22
            user:
                from_secret: ssh_name
            key:
                from_secret: ssh_key
        script:
            - cd /home/songwenwen/www/api && git pull origin master
            - pwd && ls -l
            - CGO_ENABLED=0 go build -o api
            - docker build -t api:v1 .
            - docker rm -f go-api || true
            - docker run -d --rm --name go-api -p 8001:8001 api:v1
