workspace:
  base: /data/service
  path: .

pipeline:
  build:
    image: golang:1.13.6
    # # pull: true
    environment:
      - GO111MODULE=on
      - GOPROXY=https://goproxy.cn,direct
    # secrets: [key1, key2]
    commands:
      - pwd
      - go env
      - go version
      - go build -o api
      - ls -l
      - api
