workspace:
  base: /data/service
  path: .

pipeline:
  build:
    image: golang:1.13.6
    environment:
      - GO111MODULE=on
      - GOPROXY=https://goproxy.cn,direct
    commands:
      - pwd
      - go env
      - go version
      - go test -v
      - go build -o api
      - ls -l
