version: '3'
services:
  drone-server:
    image: drone/drone:1.0.0-rc.5
    ports:
      - "10081:80"
    volumes:
      - /home/songwenwen/local/drone:/var/lib/drone/
    networks:
      - dronenet
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_HOST=49.232.18.147:10081
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_DEBUG=true
      - DRONE_GITHUB=true
      - DRONE_PROVIDER=github
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
  drone-agent:
    image: drone/agent:1.0.0-rc.5
    networks:
      - dronenet
    depends_on:
      - drone-server
    environment:
      - DRONE_RPC_SERVER=http://49.232.18.147:10081
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_DEBUG=true
networks:
  dronenet:
