version: '3'
services:
  drone-server:
    image: drone/drone:1.0.0-rc.5
    ports:
      - "10081:80"
    volumes:
      - /home/songwenwen/local/drone:/var/lib/drone/
    networks:
      - dronenet
    env_file:
      - /home/songwenwen/www/api/.server_env
  drone-agent:
    image: drone/agent:1.0.0-rc.5
    networks:
      - dronenet
    depends_on:
      - drone-server
    env_file:
      - /home/songwenwen/www/api/.agent_env
networks:
  dronenet:
